[0m16:10:14.058023 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73ad2a68fc20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73ad2b28f5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73ad2d192630>]}


============================== 16:10:14.062789 | 456cd186-c6e6-421b-a6cd-2795b3053fcf ==============================
[0m16:10:14.062789 [info ] [MainThread]: Running with dbt=1.10.11
[0m16:10:14.063900 [debug] [MainThread]: running dbt with arguments {'introspect': 'True', 'printer_width': '80', 'log_cache_events': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'write_json': 'True', 'invocation_command': 'dbt init', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'log_path': 'logs', 'partial_parse': 'True', 'log_format': 'default', 'no_print': 'None', 'profiles_dir': '/home/fenosoa/.dbt', 'warn_error': 'None', 'debug': 'False', 'cache_selected_only': 'False', 'empty': 'None', 'use_experimental_parser': 'False', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True', 'quiet': 'False'}
[0m16:10:14.101203 [info ] [MainThread]: Creating dbt configuration folder at /home/fenosoa/.dbt
[0m16:10:53.956939 [debug] [MainThread]: Starter project path: /home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/include/starter_project
[0m16:10:53.963736 [info ] [MainThread]: 
Your new dbt project "getting_started_dbt_bigquery" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:10:53.965415 [info ] [MainThread]: Setting up your profile.
[0m16:14:27.060600 [info ] [MainThread]: Profile getting_started_dbt_bigquery written to /home/fenosoa/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:14:27.084526 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 253.12363, "process_in_blocks": "10944", "process_kernel_time": 0.61985, "process_mem_max_rss": "360616", "process_out_blocks": "88", "process_user_time": 5.079771}
[0m16:14:27.088398 [debug] [MainThread]: Command `dbt init` succeeded at 16:14:27.087813 after 253.13 seconds
[0m16:14:27.090685 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73ad2f1b3d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73ad0c8a9820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73ad0b6c10a0>]}
[0m16:14:27.092954 [debug] [MainThread]: Flushing usage events
[0m16:14:32.695201 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:14:51.852552 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74bfa0c1ba10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74bf9efbd100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74bf9ea723f0>]}


============================== 16:14:51.857627 | 35d492a0-be53-46b4-aaac-209323ebf76e ==============================
[0m16:14:51.857627 [info ] [MainThread]: Running with dbt=1.10.11
[0m16:14:51.858694 [debug] [MainThread]: running dbt with arguments {'empty': 'None', 'no_print': 'None', 'send_anonymous_usage_stats': 'True', 'cache_selected_only': 'False', 'indirect_selection': 'eager', 'quiet': 'False', 'debug': 'False', 'log_cache_events': 'False', 'use_experimental_parser': 'False', 'partial_parse': 'True', 'warn_error': 'None', 'log_path': 'logs', 'invocation_command': 'dbt debug', 'target_path': 'None', 'write_json': 'True', 'fail_fast': 'False', 'profiles_dir': '/home/fenosoa/.dbt', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'printer_width': '80', 'log_format': 'default', 'version_check': 'True', 'introspect': 'True', 'use_colors': 'True', 'static_parser': 'True'}
[0m16:14:51.904191 [info ] [MainThread]: dbt version: 1.10.11
[0m16:14:51.905042 [info ] [MainThread]: python version: 3.12.3
[0m16:14:51.905635 [info ] [MainThread]: python path: /home/fenosoa/Projects/main_project/data_engineer/.python_analytics/bin/python3
[0m16:14:51.906191 [info ] [MainThread]: os info: Linux-6.8.0-63-generic-x86_64-with-glibc2.39
[0m16:15:00.206982 [info ] [MainThread]: Using profiles dir at /home/fenosoa/.dbt
[0m16:15:00.207766 [info ] [MainThread]: Using profiles.yml file at /home/fenosoa/.dbt/profiles.yml
[0m16:15:00.208466 [info ] [MainThread]: Using dbt_project.yml file at /home/fenosoa/Projects/main_project/data_engineer/project/getting-started-dbt-bigquery/dbt_project.yml
[0m16:15:00.209050 [info ] [MainThread]: adapter type: bigquery
[0m16:15:00.209602 [info ] [MainThread]: adapter version: 1.10.2
[0m16:15:00.210175 [info ] [MainThread]: Configuration:
[0m16:15:00.210727 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m16:15:00.211262 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:15:00.211841 [info ] [MainThread]: Required dependencies:
[0m16:15:00.212387 [debug] [MainThread]: Executing "git --help"
[0m16:15:00.235521 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:15:00.236835 [debug] [MainThread]: STDERR: "b''"
[0m16:15:00.237608 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:15:00.238481 [info ] [MainThread]: Connection:
[0m16:15:00.239405 [info ] [MainThread]:   method: service-account
[0m16:15:00.240377 [info ] [MainThread]:   database: dbt-learn-bq-472715-f4
[0m16:15:00.241515 [info ] [MainThread]:   execution_project: dbt-learn-bq-472715-f4
[0m16:15:00.243842 [info ] [MainThread]:   schema: dbt-learn-bq-472715-f4.stripe
[0m16:15:00.245782 [info ] [MainThread]:   location: US
[0m16:15:00.247506 [info ] [MainThread]:   priority: interactive
[0m16:15:00.248905 [info ] [MainThread]:   maximum_bytes_billed: None
[0m16:15:00.250116 [info ] [MainThread]:   impersonate_service_account: None
[0m16:15:00.251338 [info ] [MainThread]:   job_retry_deadline_seconds: None
[0m16:15:00.252758 [info ] [MainThread]:   job_retries: 1
[0m16:15:00.254848 [info ] [MainThread]:   job_creation_timeout_seconds: None
[0m16:15:00.256427 [info ] [MainThread]:   job_execution_timeout_seconds: 300
[0m16:15:00.258240 [info ] [MainThread]:   timeout_seconds: 300
[0m16:15:00.259719 [info ] [MainThread]:   client_id: None
[0m16:15:00.260365 [info ] [MainThread]:   token_uri: None
[0m16:15:00.261664 [info ] [MainThread]:   compute_region: None
[0m16:15:00.263984 [info ] [MainThread]:   dataproc_cluster_name: None
[0m16:15:00.265147 [info ] [MainThread]:   gcs_bucket: None
[0m16:15:00.266431 [info ] [MainThread]:   dataproc_batch: None
[0m16:15:00.268995 [info ] [MainThread]: Registered adapter: bigquery=1.10.2
[0m16:15:00.750380 [debug] [MainThread]: Acquiring new bigquery connection 'debug'
[0m16:15:00.751920 [debug] [MainThread]: On debug: select 1 as id
[0m16:15:00.753297 [debug] [MainThread]: Opening a new connection, currently in state init
[0m16:15:01.660800 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m16:15:01.662966 [info ] [MainThread]: [31m2 checks failed:[0m
[0m16:15:01.664191 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/fenosoa/Projects/main_project/data_engineer/project/getting-started-dbt-bigquery/dbt_project.yml> not found

[0m16:15:01.665155 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  Unable to generate access token, if you're using impersonate_service_account, make sure your initial account has the "roles/iam.serviceAccountTokenCreator" role on the account you are trying to impersonate.
  
  ('invalid_grant: Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim.'})

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m16:15:01.667042 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 9.899457, "process_in_blocks": "98496", "process_kernel_time": 0.991519, "process_mem_max_rss": "364432", "process_out_blocks": "24", "process_user_time": 7.71227}
[0m16:15:01.668619 [debug] [MainThread]: Command `dbt debug` failed at 16:15:01.668323 after 9.90 seconds
[0m16:15:01.669499 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m16:15:01.670395 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74bf9ea2f470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74bf7ebcd640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74bf7fd3ac00>]}
[0m16:15:01.671433 [debug] [MainThread]: Flushing usage events
[0m16:15:03.172722 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:17:07.543501 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2e79211af0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2e79291eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2e79212cc0>]}


============================== 16:17:07.548113 | 5e382d73-2480-4d39-bd05-edef16993625 ==============================
[0m16:17:07.548113 [info ] [MainThread]: Running with dbt=1.10.11
[0m16:17:07.549171 [debug] [MainThread]: running dbt with arguments {'partial_parse': 'True', 'no_print': 'None', 'version_check': 'True', 'empty': 'None', 'use_colors': 'True', 'invocation_command': 'dbt init', 'quiet': 'False', 'cache_selected_only': 'False', 'introspect': 'True', 'debug': 'False', 'write_json': 'True', 'warn_error': 'None', 'profiles_dir': '/home/fenosoa/.dbt', 'log_path': 'logs', 'static_parser': 'True', 'use_experimental_parser': 'False', 'fail_fast': 'False', 'indirect_selection': 'eager', 'printer_width': '80', 'send_anonymous_usage_stats': 'True', 'log_cache_events': 'False', 'log_format': 'default', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None'}
[0m16:17:17.924213 [info ] [MainThread]: A project called getting_started_dbt_bigquery already exists here.
[0m16:17:17.926177 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 10.465871, "process_in_blocks": "40", "process_kernel_time": 0.174927, "process_mem_max_rss": "98828", "process_out_blocks": "16", "process_user_time": 2.124117}
[0m16:17:17.926977 [debug] [MainThread]: Command `dbt init` succeeded at 16:17:17.926836 after 10.47 seconds
[0m16:17:17.927558 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2e79007c20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2e78f4f1a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c2e7a529340>]}
[0m16:17:17.928147 [debug] [MainThread]: Flushing usage events
[0m16:17:19.776370 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:17:36.849655 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74fa02a23ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74fa02714fb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74fa02824500>]}


============================== 16:17:36.854204 | fcd7fa33-516f-48bd-aa06-bfbbdd29116b ==============================
[0m16:17:36.854204 [info ] [MainThread]: Running with dbt=1.10.11
[0m16:17:36.855187 [debug] [MainThread]: running dbt with arguments {'version_check': 'True', 'empty': 'None', 'indirect_selection': 'eager', 'no_print': 'None', 'log_cache_events': 'False', 'send_anonymous_usage_stats': 'True', 'log_path': 'logs', 'cache_selected_only': 'False', 'invocation_command': 'dbt init', 'static_parser': 'True', 'use_experimental_parser': 'False', 'profiles_dir': '/home/fenosoa/.dbt', 'warn_error': 'None', 'write_json': 'True', 'debug': 'False', 'use_colors': 'True', 'log_format': 'default', 'partial_parse': 'True', 'introspect': 'True', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'fail_fast': 'False', 'printer_width': '80'}
[0m16:17:46.408351 [debug] [MainThread]: Starter project path: /home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/include/starter_project
[0m16:17:46.539369 [info ] [MainThread]: 
Your new dbt project "getting_started_dbt_bigquery" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:17:46.541906 [info ] [MainThread]: Setting up your profile.
[0m16:18:59.869472 [info ] [MainThread]: Profile getting_started_dbt_bigquery written to /home/fenosoa/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:18:59.872123 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 83.1056, "process_in_blocks": "1968", "process_kernel_time": 0.654723, "process_mem_max_rss": "360004", "process_out_blocks": "96", "process_user_time": 5.017077}
[0m16:18:59.873794 [debug] [MainThread]: Command `dbt init` succeeded at 16:18:59.873524 after 83.11 seconds
[0m16:18:59.874769 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74fa01b6c860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74f9e27c43b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74f9e2222f90>]}
[0m16:18:59.875641 [debug] [MainThread]: Flushing usage events
[0m16:19:01.640404 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:04:48.789726 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a3d819b54c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a3d833e6cc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a3d828af9e0>]}


============================== 17:04:48.794581 | 6b16c892-6693-4c1e-812a-8cac828ae261 ==============================
[0m17:04:48.794581 [info ] [MainThread]: Running with dbt=1.10.11
[0m17:04:48.795633 [debug] [MainThread]: running dbt with arguments {'log_path': 'logs', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'profiles_dir': '/home/fenosoa/.dbt', 'send_anonymous_usage_stats': 'True', 'write_json': 'True', 'debug': 'False', 'empty': 'None', 'printer_width': '80', 'log_cache_events': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'no_print': 'None', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init', 'cache_selected_only': 'False', 'use_colors': 'True', 'partial_parse': 'True', 'quiet': 'False', 'version_check': 'True'}
[0m17:05:06.075526 [debug] [MainThread]: Starter project path: /home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/include/starter_project
[0m17:05:06.091979 [info ] [MainThread]: 
Your new dbt project "dbt_bigquery" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:05:06.093335 [info ] [MainThread]: Setting up your profile.
[0m17:07:17.715346 [info ] [MainThread]: Profile dbt_bigquery written to /home/fenosoa/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:07:17.717960 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 149.00656, "process_in_blocks": "62488", "process_kernel_time": 0.734549, "process_mem_max_rss": "360072", "process_out_blocks": "80", "process_user_time": 5.572411}
[0m17:07:17.719885 [debug] [MainThread]: Command `dbt init` succeeded at 17:07:17.719575 after 149.01 seconds
[0m17:07:17.720999 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a3d814cc860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a3d61542450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7a3d615419d0>]}
[0m17:07:17.722428 [debug] [MainThread]: Flushing usage events
[0m17:07:19.490861 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:07:51.263082 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707b440d74d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707b443dfc80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707b440d7d70>]}


============================== 17:07:51.267791 | 966d898b-5ac6-40f0-83f8-b8708556df3a ==============================
[0m17:07:51.267791 [info ] [MainThread]: Running with dbt=1.10.11
[0m17:07:51.268793 [debug] [MainThread]: running dbt with arguments {'empty': 'None', 'debug': 'False', 'static_parser': 'True', 'warn_error': 'None', 'printer_width': '80', 'send_anonymous_usage_stats': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'write_json': 'True', 'use_colors': 'True', 'no_print': 'None', 'log_path': 'logs', 'log_format': 'default', 'introspect': 'True', 'partial_parse': 'True', 'use_experimental_parser': 'False', 'profiles_dir': '/home/fenosoa/.dbt', 'quiet': 'False', 'version_check': 'True', 'fail_fast': 'False', 'log_cache_events': 'False', 'indirect_selection': 'eager', 'target_path': 'None', 'cache_selected_only': 'False'}
[0m17:07:51.280586 [info ] [MainThread]: dbt version: 1.10.11
[0m17:07:51.281724 [info ] [MainThread]: python version: 3.12.3
[0m17:07:51.282756 [info ] [MainThread]: python path: /home/fenosoa/Projects/main_project/data_engineer/.python_analytics/bin/python3
[0m17:07:51.283801 [info ] [MainThread]: os info: Linux-6.8.0-63-generic-x86_64-with-glibc2.39
[0m17:07:54.147864 [info ] [MainThread]: Using profiles dir at /home/fenosoa/.dbt
[0m17:07:54.148631 [info ] [MainThread]: Using profiles.yml file at /home/fenosoa/.dbt/profiles.yml
[0m17:07:54.149254 [info ] [MainThread]: Using dbt_project.yml file at /home/fenosoa/Projects/main_project/data_engineer/project/getting-started-dbt-bigquery/dbt_project.yml
[0m17:07:54.149967 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m17:07:54.151343 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 2.9665966, "process_in_blocks": "0", "process_kernel_time": 0.42018, "process_mem_max_rss": "361972", "process_out_blocks": "8", "process_user_time": 4.809614}
[0m17:07:54.152361 [debug] [MainThread]: Command `dbt debug` failed at 17:07:54.152221 after 2.97 seconds
[0m17:07:54.152993 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707b43967fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707b43a30380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x707b23ef7d10>]}
[0m17:07:54.153639 [debug] [MainThread]: Flushing usage events
[0m17:07:55.626547 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:23:44.714695 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796ac3649f70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796ac4b9a480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796ac3954680>]}


============================== 17:23:44.770027 | 4c2f5fc8-8c24-44f1-b1a6-fcb823dd8596 ==============================
[0m17:23:44.770027 [info ] [MainThread]: Running with dbt=1.10.11
[0m17:23:44.772428 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'log_cache_events': 'False', 'no_print': 'None', 'version_check': 'True', 'fail_fast': 'False', 'warn_error': 'None', 'introspect': 'True', 'use_experimental_parser': 'False', 'invocation_command': 'dbt init', 'quiet': 'False', 'send_anonymous_usage_stats': 'True', 'log_path': 'logs', 'cache_selected_only': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'use_colors': 'True', 'profiles_dir': '/home/fenosoa/.dbt', 'static_parser': 'True', 'write_json': 'True', 'log_format': 'default', 'partial_parse': 'True', 'target_path': 'None', 'empty': 'None', 'debug': 'False', 'indirect_selection': 'eager'}
[0m17:28:30.793680 [error] [MainThread]: Encountered an error:

[0m17:28:30.840403 [error] [MainThread]: Traceback (most recent call last):
  File "/home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/task/init.py", line 324, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/task/init.py", line 278, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/click/termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:28:30.866025 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 286.32208, "process_in_blocks": "42880", "process_kernel_time": 0.516492, "process_mem_max_rss": "98620", "process_out_blocks": "24", "process_user_time": 3.533735}
[0m17:28:30.868509 [debug] [MainThread]: Command `dbt init` failed at 17:28:30.867904 after 286.33 seconds
[0m17:28:30.870900 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796ac3954680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796ac2d0bf80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x796ac3cf8410>]}
[0m17:28:30.873874 [debug] [MainThread]: Flushing usage events
[0m17:28:32.786955 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:34:10.805210 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eda5ecdef30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eda5f899790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eda608efce0>]}


============================== 17:34:10.809767 | 62f3e867-4db7-460b-b8d6-61c0806099ae ==============================
[0m17:34:10.809767 [info ] [MainThread]: Running with dbt=1.10.11
[0m17:34:10.810792 [debug] [MainThread]: running dbt with arguments {'no_print': 'None', 'cache_selected_only': 'False', 'partial_parse': 'True', 'static_parser': 'True', 'introspect': 'True', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'write_json': 'True', 'fail_fast': 'False', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'profiles_dir': '/home/fenosoa/.dbt', 'log_path': 'logs', 'empty': 'None', 'printer_width': '80', 'log_format': 'default', 'send_anonymous_usage_stats': 'True', 'debug': 'False', 'invocation_command': 'dbt init', 'use_experimental_parser': 'False', 'target_path': 'None', 'indirect_selection': 'eager', 'log_cache_events': 'False'}
[0m17:34:20.869006 [debug] [MainThread]: Starter project path: /home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/include/starter_project
[0m17:34:20.901994 [info ] [MainThread]: 
Your new dbt project "dbt_bigquery" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:34:20.903516 [info ] [MainThread]: Setting up your profile.
[0m17:35:40.873713 [info ] [MainThread]: Profile dbt_bigquery written to /home/fenosoa/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:35:40.878093 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 90.17777, "process_in_blocks": "203032", "process_kernel_time": 1.365255, "process_mem_max_rss": "358732", "process_out_blocks": "88", "process_user_time": 7.233229}
[0m17:35:40.882633 [debug] [MainThread]: Command `dbt init` succeeded at 17:35:40.881923 after 90.18 seconds
[0m17:35:40.885595 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eda5f7624b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eda3f891a00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7eda3f8c2810>]}
[0m17:35:40.888812 [debug] [MainThread]: Flushing usage events
[0m17:35:42.681035 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:13:59.868036 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73526f356330>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73526e7a91f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x735270da42c0>]}


============================== 18:13:59.927824 | 0bc6c63a-7d4b-4875-b65d-369b1e784018 ==============================
[0m18:13:59.927824 [info ] [MainThread]: Running with dbt=1.10.11
[0m18:13:59.929507 [debug] [MainThread]: running dbt with arguments {'static_parser': 'True', 'log_format': 'default', 'send_anonymous_usage_stats': 'True', 'empty': 'None', 'indirect_selection': 'eager', 'profiles_dir': '/home/fenosoa/.dbt', 'introspect': 'True', 'partial_parse': 'True', 'target_path': 'None', 'printer_width': '80', 'use_colors': 'True', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'write_json': 'True', 'log_cache_events': 'False', 'use_experimental_parser': 'False', 'log_path': 'logs', 'quiet': 'False', 'fail_fast': 'False', 'cache_selected_only': 'False', 'no_print': 'None', 'invocation_command': 'dbt init'}
[0m18:14:11.978787 [debug] [MainThread]: Starter project path: /home/fenosoa/Projects/main_project/data_engineer/.python_analytics/lib/python3.12/site-packages/dbt/include/starter_project
[0m18:14:12.002025 [info ] [MainThread]: 
Your new dbt project "dbt_bigquery_src" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:14:12.004126 [info ] [MainThread]: Setting up your profile.
[0m18:15:00.643457 [info ] [MainThread]: Profile dbt_bigquery_src written to /home/fenosoa/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:15:00.674963 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 60.92633, "process_in_blocks": "203376", "process_kernel_time": 1.359088, "process_mem_max_rss": "356800", "process_out_blocks": "88", "process_user_time": 7.375439}
[0m18:15:00.677275 [debug] [MainThread]: Command `dbt init` succeeded at 18:15:00.676878 after 60.93 seconds
[0m18:15:00.678186 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7352725b7d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73524f44c3b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x73524f344d40>]}
[0m18:15:00.679499 [debug] [MainThread]: Flushing usage events
[0m18:15:02.695394 [debug] [MainThread]: An error was encountered while trying to flush usage events
